### ISSUE TITLE
Anchor sprite bottom to slope

### ISSUE THREAD

**Issue by yaegerbomb** [hexus/phaser-arcade-slopes#10]
Is there a way to make sure that the sprite that is colliding with the slopes rotates in the direction to where the slope is?

Scenario: Sprite is a roller coaster cart. As it goes up the hill i want the cart to stay attached to the ground so that sprite needs to rotate to match the slope. Same for going downhill.

Am I provided with information in my collision callback that might help me achieve the correct rotation?

**Comment by hexus** [comment]
While this was only intended for axis-aligned bounding boxes for now (and circles soon) there is data given to the physics body that could be useful to you for this.

In your callback, access `sprite.body.slopes.sat.response`. It's an [SAT.js](https://github.com/jriecken/sat-js#satresponse) response object from the collision that gives you information about the collision; the direction and the depth.

Keep in mind, this response will always be in regards to the original axis-aligned bounding box so it might not be easy to get the consistent results you want. This plugin hasn't been written with rotation in mind, but in future, it could...

**Comment by yaegerbomb** [comment]
Awesome. It will be a good start for now and that is all I was looking for with the initial question. Thanks!

**Comment by hexus** [comment]
Nice one. Happy to have helped. :+1:
