### ISSUE TITLE
Update typescript definitions for 0.2.0

### ISSUE THREAD

**Issue by hexus** [hexus/phaser-arcade-slopes#30]
The Typescript definitions are out of date after the new features have been added.

@IkonOne, would you be interested in making a PR for this?

I can totally tackle it myself but I have no dev environment for Typescript (never used it), so I couldn't verify their correctness.

**Comment by IkonOne** [comment]
Sure I'll get one out over the weekend.  Thanks for the heads up.

**Comment by hexus** [comment]
Awesome! No worries, thank you kindly.

**Comment by IkonOne** [comment]
No problem.  Just shout at me when the api changes and I'll be happy to send a PR your way when I am free!
