### ISSUE TITLE
Bodies not colliding

### ISSUE THREAD

**Issue by dave-kennedy** [hexus/phaser-arcade-slopes#43]
I'm not sure what I did wrong here, but my player sprite falls straight through the floor. When I enable debugging, it appears the bodies are only being created for some tiles and not others.

![screen shot 2017-05-26 at 16 45 48-fullpage](https://cloud.githubusercontent.com/assets/13735532/26514935/cf86a362-4232-11e7-89a4-9e5478b50b7a.png)

I've uploaded the code to https://github.com/dave-kennedy/Platformer.

**Comment by hexus** [comment]
Thanks for submitting an issue!

I'm able to replicate this too, without setting the colliding tile index range on the `Phaser.Tilemap` object. 

This should either be mentioned in the readme or silently handled in the plugin somehow, if possible.

![image](https://cloud.githubusercontent.com/assets/2626789/26515881/1cc59108-4277-11e7-9196-ec8cef32e920.png)

For now, placing this line of code:

```js
this.map.setCollisionBetween(513, 551, true, 'Tile Layer 2');
```

**Before** this line in your fourth level state:

https://github.com/dave-kennedy/Platformer/blob/cfa7dbdf2f8a7274b02a897f25cf2adf8d5754c2/src/State/Level4.js#L46

Should hopefully fix your issue.

If not, I may be using the wrong numbers!

**Comment by dave-kennedy** [comment]
That did the trick. Thanks!
