### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by Majirefy** [hexus/phaser-arcade-slopes#47]
I noticed npm package not update for 3 months.

Hope it will update with new release. Thanks~

**Comment by hexus** [comment]
Thank you for reminding me, I need to keep on top of that!

**Comment by hexus** [comment]
I've noticed it wasn't me that published this, but @log1x.

@log1x, would you mind me taking control over the phaser-arcade-slopes name on npm? I can publish all versions that way, including an upcoming 0.3.0-alpha.

**Comment by Log1x** [comment]
No problem.

I added you as a "Collaborator" on npmjs-- just let me know when you're all set and I can remove myself to give you full control.

**Comment by hexus** [comment]
Man, working with npm is frustrating. I just want to unpublish the package and republish it with all the correct versions! :angry:

**Comment by Log1x** [comment]
I agree it's a pain. After working with PHP and using Composer/Packagist-- I really don't understand npm's publish system.

Would it help if I unpublish / attempt to delete the package so you can start from scratch?

**Comment by hexus** [comment]
Composer and Packagist do it perfectly. 

I've been attempting to remove it myself but keep getting hit with 403s. I have since removed you from the collaborators but I'll add you back now just in case that works.

**Comment by hexus** [comment]
I think it's to do with their policy to prevent that infamous `left-pad` debacle from ever happening again.

I'll email their support team.

**Comment by hexus** [comment]
@Majirefy, you can use npm to pull GitHub repositories as dependencies like so:

```json
"dependencies": {
    "phaser-arcade-slopes": "hexus/phaser-arcade-slopes#v0.2.0"
}
```

Where everything after the `#` is just a tag. Hope this helps.

Starting to remember why I gave up with npm before. :joy:

**Comment by Majirefy** [comment]
Thanks! @hexus @Log1x

**Comment by hexus** [comment]
They got back and said unpublished versions can never be republished, and I can't delete the package, only deprecate it and choose a new name.

So I'll release 0.2.1 at some point and when I do, that will be published to NPM. I recommend just using the method above though, to give you proper access to all the versions.
