### ISSUE TITLE
Doesn't appear to be compatible with Phaser 2.5.0

### ISSUE THREAD

**Issue by iCodeForBananas** [hexus/phaser-arcade-slopes#5]
This works:
`//cdn.rawgit.com/photonstorm/phaser/c4cded108fd39d25b9bb1d56a1e78d96c150269f/build/phaser.min.js`

This throws an error:
`//cdnjs.cloudflare.com/ajax/libs/phaser/2.5.0/phaser.min.js`

![screen shot 2016-06-19 at 8 55 40 am](https://cloud.githubusercontent.com/assets/8272012/16178405/ac9abfb2-35fb-11e6-8d1c-54b2f463848f.png)

![screen shot 2016-06-19 at 8 55 52 am](https://cloud.githubusercontent.com/assets/8272012/16178406/ac9ae906-35fb-11e6-9fc1-82b98c12ce83.png)

**Comment by hexus** [comment]
Yes, right now it's definitely not compatible with anything above 2.4.8, because the API of a method that the plugin overrides (separateTile) changed.

Thanks for making an issue for this. It will be resolved in the next version. :)

**Comment by hexus** [comment]
All sorted buddy!

Commit 86c68867 for v0.1.1.
