### ISSUE TITLE
Maybe mention that the order you set body related properties matters

### ISSUE THREAD

**Issue by iCodeForBananas** [hexus/phaser-arcade-slopes#6]
Fantastic job on this! :)
This is easily core worthy.

<img width="459" alt="playerspritehandler_js_ _rangersteve" src="https://cloud.githubusercontent.com/assets/8272012/16232989/981c8a66-3781-11e6-9c51-cdfb60576319.png">

<img width="426" alt="playerspritehandler_js_ _rangersteve" src="https://cloud.githubusercontent.com/assets/8272012/16233004/a90beb64-3781-11e6-8144-1c255877c640.png">

**Comment by hexus** [comment]
Thank you! I'm glad you like it.

Thanks for explaining this issue so clearly, I'll clarify in the readme and maybe even find a way to fix this so the first case works okay.

**Comment by hexus** [comment]
Sorted in v0.1.1. Should be a little clearer now. It's only the size of the sprite that matters, as `slopes.enable()` creates the body's SAT.js polygon used by the collision solver.
